<a href="https://colab.research.google.com/github/milkchoco3524/ABCD_A/blob/main/20240506_CNN_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. CNN을 구성하는 레이어

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

배치 크기 x 채널 x 높이(height) x 너비(widht)

- 배치 크기 : 1
- 채널 : 1 (그레이스케일 1, 컬러3)
- 높이(픽셀) : 28
- 너비(픽셀) : 28

In [9]:
## Pooling example
input_example = torch.tensor([[[0,1,2], [3,4,5,], [6,7,8,]]])
print(input_example)
# max pooling
max_pooling_layer = nn.MaxPool2d(kernel_size=2, stride=1)
print(max_pooling_layer)
print(max_pooling_layer(input_example))
# average pooling
average_pooling_layer = torch.nn.AvgPool2d(kernel_size=2, stride=1)
print(average_pooling_layer)
print(average_pooling_layer(input_example))

tensor([[[0, 1, 0, 2],
         [3, 4, 5, 0],
         [6, 7, 8, 0]]])
MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)
tensor([[[4, 5, 5],
         [7, 8, 8]]])
AvgPool2d(kernel_size=2, stride=1, padding=0)
tensor([[[2, 2, 1],
         [5, 6, 3]]])


In [12]:
## Quiz!!
input_example = torch.tensor([[[12, 20, 30, 0.0], [20, 12, 2, 0], [0, 70, 5, 2], [8, 2, 90, 3]]])
print(input_example)

max_pooling_layer = nn.MaxPool2d(kernel_size=2, stride=2)
print('\nmaxpooling:\n', max_pooling_layer(input_example))

average_pooling_layer = torch.nn.AvgPool2d(kernel_size=2, stride=2)
print('\naverage pooling:\n', average_pooling_layer(input_example))

tensor([[[12., 20., 30.,  0.],
         [20., 12.,  2.,  0.],
         [ 0., 70.,  5.,  2.],
         [ 8.,  2., 90.,  3.]]])

maxpooling:
 tensor([[[20., 30.],
         [70., 90.]]])

average pooling:
 tensor([[[16.,  8.],
         [20., 25.]]])


## Input

In [13]:
inputs = torch.Tensor(1, 1, 32, 32)

inputs.shape

torch.Size([1, 1, 32, 32])

## 첫번째 Conv2D

In [15]:
conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, padding=1)

print(conv1)


Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


## 두번째 Conv2D

In [17]:
conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

print(conv2)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


## MaxPooling

In [19]:
pool = nn.MaxPool2d(kernel_size=2)

print(pool)

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)


## 넣어보기

In [27]:
out = conv1(inputs)

print(out.shape)

torch.Size([1, 32, 32, 32])


In [28]:
out = pool(out)

print(out.shape)

torch.Size([1, 32, 16, 16])


In [29]:
out = conv2(out)

print(out.shape)

torch.Size([1, 64, 16, 16])


In [30]:
out = pool(out)

print(out.shape)

torch.Size([1, 64, 8, 8])


## Flatten

첫번째 차원인 배치 차원은 그대로 두고 나머지는 펼쳐라

In [31]:
out = out.view(out.size(0), -1)

print(out.shape)

torch.Size([1, 4096])


## Dense (Fully connected)

In [32]:
fc = nn.Linear(4096, 10)

out = fc(out)

print(out.shape)
print(out)

torch.Size([1, 10])
tensor([[ 1.5102e+33,  2.7599e+33, -1.6710e+33, -3.7080e+33, -5.9685e+33,
         -1.5250e+33,  3.6987e+33, -7.0365e+33, -3.5417e+33,  6.0959e+33]],
       grad_fn=<AddmmBackward0>)
